[package]
name = "marching_cubes"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.14.1", features = ["wayland"] }
bevy-inspector-egui = "0.25.1"
bevy_panorbit_camera = "0.19.1"
